/**
 * This class represent content on the platform.
 * Stores information of a content created.
 *
 * @author (Rebecca)
 * @version (Oct.16th/23)
 */
//import Date class from Java library to create real time generated dates
import java.util.Date;
public class Content{
    //declare variables for each content
        //create a variable for the content's ID
        private long lngContentID;
            //using long because FaceBook has roughly 2.5 trillion posts
        //create a variable to store the content of a post or comment
        private String strMessage;
        //create a variable for the time in which the content is made
        private Date datTimestamp;
    
    //constructors
    public Content(long ID, String M){
        //parameters: ID = content ID; M = message associated with the content
        
        //initialize the instance variables
        this.lngContentID = ID;
        this.strMessage = M;
        this.datTimestamp = new Date();
            //date is not passed through the parameter because it is autogenerated by the program
    }
        
    //toString method to format the output
    public String toString(){
        //return the formated string back to where it was called
        return this.strMessage;
    }
    
    //getters for all private variables necessarily
    public long getContentID(){
        return lngContentID;
    }
    public String getContent(){
        return strMessage;
    }
    public Date getTimestamp(){
        return datTimestamp;
    }
}
