/**
 * This class represent posts made by users
 * Stores information of a single user's post.
 *
 * @author (Rebecca)
 * @version (Oct.16th/23)
 */
//import ArrayList class library to access all functions of an arraylist
import java.util.ArrayList;
//import Date class from Java library to create real time generated dates
import java.util.Date;
public class Posts{
    //declare variables for a post
        //create a variable for the post ID
        private long lngPostID;
            //using long because FaceBook has roughly 2.5 trillion posts
        //create a variable to store the content
        private Content c1;
        //create a variable to store the current time when the post is publisized
        private Date d1;
        //create an arraylist to store all comments under the post
        ArrayList<Comments> PostsComments;
        
        //create a variable to store the number of posts created ever
            //the variable will be static as it is counting throughout all post objects
        static long lngNumPost = 0;
    
    //counter for number of posts for all users, aka the post ID
    public static void CountPosts(){
        //increase the value of lngNumPost by one every time this method is called
        lngNumPost += 1;
    }
        
    //constructors
    public Posts(long NP, Content C){
        //parameters: NP = NumPost, the total number of posts by all users; C = content, could be text, images or video
        
        //initialize the instance variables
        this.lngPostID = NP;
        this.c1 = C;
        this.d1 = new Date();
            //date is not passed through the parameter because it is autogenerated by the program
        //create the an arraylist for all users
        this.PostsComments = new ArrayList<Comments>();
    }
    
    //toString method to format the output
    public String toString(){
        //return the formated string back to where it was called
        return this.c1.toString();
    }
}
